apiVersion: v1
kind: Service
metadata:
  namespace: cdielk
  name: elasticsearch-ingest
  labels:
    app: elasticsearch
    role: ingest
spec:
  ports:
  - port: 9200
    name: client
  - port: 9300
    name: transport
  selector:
    app: elasticsearch
    role: ingest