apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: cdielk
  name: kibana
  labels:
    app: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
      - name: kibana
        image: docker.elastic.co/kibana/kibana:7.6.2
        ports:
        - containerPort: 5601
          name: webinterface
        env:
        - name: ELASTICSEARCH_HOSTS
          value: "https://elasticsearch-ingest.cdielk.svc.cluster.local:9200"
        - name: ELASTICSEARCH_USER
          value: "elastic"
        - name: ELASTICSEARCH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: password
        volumeMounts:
        - name: config
          mountPath: /usr/share/kibana/config/kibana.yml
          readOnly: true
          subPath: kibana.yml
        - name: elasticsearch-cert
          mountPath: /usr/share/kibana/config/cert
        resources:
          requests:
              memory: "512Mi"
      volumes:
      - name: config
        configMap:
          name: kibana-config
      - name: elasticsearch-cert
        secret:
         secretName: elasticsearch-cert
