apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: cdielk
  name: elasticsearch-master
  labels:
    app: elasticsearch
    role: master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
      role: master
  template:
    metadata:
      labels:
        app: elasticsearch
        role: master
    spec:
      containers:
      - name: elasticsearch-master
        image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
        env:
        - name: CLUSTER_NAME
          value: elasticsearch
        - name: NODE_NAME
          value: elasticsearch-master
        - name: NODE_LIST
          value: elasticsearch-master,elasticsearch-data,elasticsearch-ingest
        - name: MASTER_NODES
          value: elasticsearch-master
        - name: "ES_JAVA_OPTS"
          value: "-Xms2g -Xmx2g"
        - name: ELASTIC_USERNAME
          value: elastic
        - name: ELASTIC_PASSWORD
          valueFrom:
           secretKeyRef:
             name: mysecret
             key: password 
        ports:
        - containerPort: 9300
          name: transport
        - containerPort: 9200
          name: tcp
        volumeMounts:
        - name: config
          mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
          readOnly: true
          subPath: elasticsearch.yml
        - name: storage
          mountPath: /data
        - name: elasticsearch-cert     
          mountPath: /usr/share/elasticsearch/config/cert
          readOnly: true
        resources:
          requests:
             memory: "512Mi"
      volumes:
      - name: config
        configMap:
          name: es-master-config
      - name: storage
        emptyDir:
          medium: ""
      - name: elasticsearch-cert
        secret:
            secretName: elasticsearch-cert
      initContainers:
      - name: increase-vm-max-map
        image: busybox
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true
