apiVersion: v1
kind: ConfigMap
metadata:
  namespace: cdielk
  name: es-master-config
  labels:
    app: elasticsearch
    role: master
data:
  elasticsearch.yml: |-
    cluster.name: ${CLUSTER_NAME}
    node.name: ${NODE_NAME}
    discovery.seed_hosts: ${NODE_LIST}
    cluster.initial_master_nodes: ${MASTER_NODES}
    network.host: 0.0.0.0

    node:
      master: true
      data: false
      ingest: false

    xpack.security.enabled: true
    xpack.monitoring.collection.enabled: false
    xpack.security.http.ssl.enabled: true
    xpack.security.transport.ssl.enabled: true
    xpack.security.transport.ssl.verification_mode: none
    xpack.security.transport.ssl.keystore.path: /usr/share/elasticsearch/config/cert/container.p12
    xpack.security.transport.ssl.truststore.path: /usr/share/elasticsearch/config/cert/container.p12
    xpack.security.http.ssl.keystore.path: /usr/share/elasticsearch/config/cert/container.p12
    xpack.security.transport.ssl.truststore.password: Welcome@321
    xpack.security.http.ssl.keystore.password: Welcome@321
    xpack.security.transport.ssl.keystore.password: Welcome@321
